# H2 Database configuration
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.datasource.url=jdbc:h2:mem:database
# JWT configuration
security.jwt.token.secret-key=/BWxvVt/eMsTVSq+RI9kRCrZKK38KNGIWi7ilxCg9So=
security.jwt.token.expire-length=3600000
payment.toss.client-key=test_ck_D5GePWvyJnrK0W0k6q8gLzN97Eoq
