spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.datasource.url=jdbc:h2:mem:database
spring.sql.init.mode=always
spring.sql.init.data-locations=classpath:mock-themes.sql, classpath:mock-times.sql, classpath:mock-reservations.sql
spring.datasource.hikari.maximum-pool-size=30
logging.level.org.springframework.transaction.interceptor=trace
logging.level.org.springframework.jdbc.datasource.DataSourceTransactionManager=DEBUG
toss.base-url=https://api.tosspayments.com
toss.client-key=test_gck_docs_Ovk5rk1EwkEbP0W43n07xlzm
toss.secret-key=test_gsk_docs_OaPz8L5KdmQXkzRz3y47BMw6
toss.connect-timeout-ms=1000
toss.read-timeout-ms=2000
toss.max-attempts=3

rate-limit.capacity=5
rate-limit.refill-per-second=1.0


outbound-rate-limit.capacity=5
outbound-rate-limit.refill-per-second=1.0
