spring.h2.console.enabled=false
spring.datasource.url=jdbc:mysql://localhost:3306/roomescape?serverTimezone=Asia/Seoul
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.sql.init.mode=always
spring.sql.init.platform=mysql