spring:
  config:
    activate:
      on-profile: "dev"
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:database
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
  sql.init.mode: never
