INSERT INTO theme (name, description, thumbnail_image_url, price, is_active)
VALUES ('화이트노이즈', '실험실에 남겨진 단서를 수집해 기묘한 송출 사고의 원인을 밝혀내는 SF 추리 테마', 'https://picsum.photos/seed/whitenoise/800/600',
        28000, 1),
       ('클락워크 호텔', '멈춰버린 호텔 시계를 다시 움직이기 위해 숨겨진 객실 기록을 파헤치는 미스터리 테마',
        'https://picsum.photos/seed/clockworkhotel/800/600', 32000, 1),
       ('선셋 다이브', '붉은 노을 아래 폐쇄 직전의 해양 연구소에서 탈출하는 어드벤처 테마', 'https://picsum.photos/seed/sunsetdive/800/600', 30000, 1),
       ('스모크 스테이지', '무대 붕괴 직전의 공연장을 복구하며 공연을 완성하는 퍼포먼스 테마', 'https://picsum.photos/seed/smokestage/800/600', 26000, 1),
       ('문라이트 아카이브', '봉인된 기록보관소에서 잃어버린 이름을 되찾는 감성 판타지 테마', 'https://picsum.photos/seed/moonlightarchive/800/600', 35000, 1),
       ('네온 디스트릭트', '통제 불능이 된 미래 도시의 전력망을 복구하며 진실을 추적하는 사이버펑크 테마', 'https://picsum.photos/seed/neondistrict/800/600',
        38000, 1),
       ('블랙아웃 터널', '정전된 지하 터널 속에서 실종된 탐사대의 흔적을 따라가는 스릴러 테마', 'https://picsum.photos/seed/blackouttunnel/800/600', 29000, 1),
       ('윈터 캐빈', '폭설로 고립된 산장 안에서 숨겨진 사건의 진실을 밝혀내는 서스펜스 테마', 'https://picsum.photos/seed/wintercabin/800/600', 31000, 1),
       ('페이퍼 뮤지엄', '사라진 전시 작품과 왜곡된 기록을 복원하는 추리형 아트 테마', 'https://picsum.photos/seed/papermuseum/800/600', 27000, 1),
       ('스톰 브레이커', '거대한 폭풍이 다가오는 항구 도시에서 재난을 막아내는 액션 테마', 'https://picsum.photos/seed/stormbreaker/800/600', 36000, 1),
       ('크림슨 룸', '붉게 물든 밀실 속 단서를 조합해 연쇄 사건의 범인을 추적하는 범죄 추리 테마', 'https://picsum.photos/seed/crimsonroom/800/600', 33000, 1),
       ('에코 플래닛', '붕괴 직전의 생태 행성에서 마지막 생명 신호를 복원하는 SF 탐험 테마', 'https://picsum.photos/seed/echoplanet/800/600', 34000, 1),
       ('라스트 브로드캐스트', '끊어진 라디오 송출을 복구하며 숨겨진 메시지를 해독하는 레트로 감성 테마',
        'https://picsum.photos/seed/lastbroadcast/800/600', 25000, 1),
       ('오로라 캠프', '극지 탐사 기지에서 벌어진 미스터리 사건을 조사하는 생존 테마', 'https://picsum.photos/seed/auroracamp/800/600', 37000, 1),
       ('더스트 팩토리', '버려진 공장의 생산 라인을 재가동하며 숨겨진 실험 기록을 찾는 산업 스릴러 테마', 'https://picsum.photos/seed/dustfactory/800/600', 30000, 1);


INSERT INTO reservation_time (start_at, status)
VALUES ('10:00:00', 'ACTIVE'),
       ('11:30:00', 'ACTIVE'),
       ('13:00:00', 'ACTIVE'),
       ('14:30:00', 'ACTIVE'),
       ('16:00:00', 'ACTIVE'),
       ('18:00:00', 'ACTIVE'),
       ('19:30:00', 'ACTIVE');

INSERT INTO reservation_slot (date, theme_id, time_id)
VALUES (DATEADD('DAY', -1, CURRENT_DATE), 1, 1),
       (DATEADD('DAY', -1, CURRENT_DATE), 2, 2),
       (DATEADD('DAY', -1, CURRENT_DATE), 3, 3),
       (DATEADD('DAY', -2, CURRENT_DATE), 1, 2),
       (DATEADD('DAY', -2, CURRENT_DATE), 2, 3),
       (DATEADD('DAY', -2, CURRENT_DATE), 4, 4),
       (DATEADD('DAY', -3, CURRENT_DATE), 1, 3),
       (DATEADD('DAY', -3, CURRENT_DATE), 3, 4),
       (DATEADD('DAY', -3, CURRENT_DATE), 5, 5),
       (DATEADD('DAY', -4, CURRENT_DATE), 1, 4),
       (DATEADD('DAY', -4, CURRENT_DATE), 2, 5),
       (DATEADD('DAY', -4, CURRENT_DATE), 4, 6),
       (DATEADD('DAY', -5, CURRENT_DATE), 1, 5),
       (DATEADD('DAY', -5, CURRENT_DATE), 3, 6),
       (DATEADD('DAY', -5, CURRENT_DATE), 5, 7),
       (DATEADD('DAY', -6, CURRENT_DATE), 1, 6),
       (DATEADD('DAY', -6, CURRENT_DATE), 2, 7),
       (DATEADD('DAY', -7, CURRENT_DATE), 1, 7),
       (DATEADD('DAY', -7, CURRENT_DATE), 3, 1),
       (DATEADD('DAY', -8, CURRENT_DATE), 2, 4),
       (DATEADD('DAY', -8, CURRENT_DATE), 4, 5),
       (DATEADD('DAY', -9, CURRENT_DATE), 1, 1),
       (DATEADD('DAY', -9, CURRENT_DATE), 5, 2),
       (DATEADD('DAY', -10, CURRENT_DATE), 1, 2),
       (DATEADD('DAY', -10, CURRENT_DATE), 2, 3),
       (DATEADD('DAY', -11, CURRENT_DATE), 3, 4),
       (DATEADD('DAY', -11, CURRENT_DATE), 1, 5),
       (DATEADD('DAY', -12, CURRENT_DATE), 4, 6),
       (DATEADD('DAY', -12, CURRENT_DATE), 1, 7),
       (DATEADD('DAY', -13, CURRENT_DATE), 5, 1),
       (DATEADD('DAY', 1, CURRENT_DATE), 1, 1);

INSERT INTO reservation (name, slot_id, status, active_status, created_at)
VALUES ('이프', 1, 'RESERVED', 'ACTIVE', CURRENT_TIMESTAMP),
       ('도윤', 2, 'RESERVED', 'ACTIVE', CURRENT_TIMESTAMP),
       ('서윤', 3, 'RESERVED', 'ACTIVE', CURRENT_TIMESTAMP),
       ('이프', 4, 'RESERVED', 'ACTIVE', CURRENT_TIMESTAMP),
       ('지우', 5, 'RESERVED', 'ACTIVE', CURRENT_TIMESTAMP),
       ('시우', 6, 'RESERVED', 'ACTIVE', CURRENT_TIMESTAMP),
       ('이프', 7, 'RESERVED', 'ACTIVE', CURRENT_TIMESTAMP),
       ('예준', 8, 'RESERVED', 'ACTIVE', CURRENT_TIMESTAMP),
       ('서준', 9, 'RESERVED', 'ACTIVE', CURRENT_TIMESTAMP),
       ('이프', 10, 'RESERVED', 'ACTIVE', CURRENT_TIMESTAMP),
       ('수아', 11, 'RESERVED', 'ACTIVE', CURRENT_TIMESTAMP),
       ('이준', 12, 'RESERVED', 'ACTIVE', CURRENT_TIMESTAMP),
       ('이프', 13, 'RESERVED', 'ACTIVE', CURRENT_TIMESTAMP),
       ('주원', 14, 'RESERVED', 'ACTIVE', CURRENT_TIMESTAMP),
       ('하린', 15, 'RESERVED', 'ACTIVE', CURRENT_TIMESTAMP),
       ('이프', 16, 'RESERVED', 'ACTIVE', CURRENT_TIMESTAMP),
       ('윤우', 17, 'RESERVED', 'ACTIVE', CURRENT_TIMESTAMP),
       ('이프', 18, 'RESERVED', 'ACTIVE', CURRENT_TIMESTAMP),
       ('은우', 19, 'RESERVED', 'ACTIVE', CURRENT_TIMESTAMP),
       ('이프', 20, 'RESERVED', 'ACTIVE', CURRENT_TIMESTAMP),
       ('태윤', 21, 'RESERVED', 'ACTIVE', CURRENT_TIMESTAMP),
       ('유진', 22, 'RESERVED', 'ACTIVE', CURRENT_TIMESTAMP),
       ('현우', 23, 'RESERVED', 'ACTIVE', CURRENT_TIMESTAMP),
       ('지호', 24, 'RESERVED', 'ACTIVE', CURRENT_TIMESTAMP),
       ('가은', 25, 'RESERVED', 'ACTIVE', CURRENT_TIMESTAMP),
       ('지후', 26, 'RESERVED', 'ACTIVE', CURRENT_TIMESTAMP),
       ('아윤', 27, 'RESERVED', 'ACTIVE', CURRENT_TIMESTAMP),
       ('유나', 28, 'RESERVED', 'ACTIVE', CURRENT_TIMESTAMP),
       ('건우', 29, 'RESERVED', 'ACTIVE', CURRENT_TIMESTAMP),
       ('다온', 30, 'RESERVED', 'ACTIVE', CURRENT_TIMESTAMP),
       ('이프', 31, 'RESERVED', 'ACTIVE', DATEADD('second', 0, CURRENT_TIMESTAMP)),
       ('라텔', 31, 'WAITING', 'ACTIVE', DATEADD('second', 1, CURRENT_TIMESTAMP)),
       ('찰리', 31, 'WAITING', 'ACTIVE', DATEADD('second', 2, CURRENT_TIMESTAMP)),
       ('에코', 31, 'WAITING', 'ACTIVE', DATEADD('second', 3, CURRENT_TIMESTAMP));
