-- 예약별 날짜/시간/테마 조합 (오늘부터 6일 후까지 동적 세팅)
INSERT INTO time_slot (date, time_id, theme_id) VALUES (DATEADD('DAY', 6, CURRENT_DATE), 1, 1);
INSERT INTO time_slot (date, time_id, theme_id) VALUES (DATEADD('DAY', 5, CURRENT_DATE), 2, 1);
INSERT INTO time_slot (date, time_id, theme_id) VALUES (DATEADD('DAY', 4, CURRENT_DATE), 3, 1);
INSERT INTO time_slot (date, time_id, theme_id) VALUES (DATEADD('DAY', 3, CURRENT_DATE), 4, 1);
INSERT INTO time_slot (date, time_id, theme_id) VALUES (DATEADD('DAY', 2, CURRENT_DATE), 5, 1);
INSERT INTO time_slot (date, time_id, theme_id) VALUES (DATEADD('DAY', 1, CURRENT_DATE), 6, 1);
INSERT INTO time_slot (date, time_id, theme_id) VALUES (CURRENT_DATE, 7, 1);
INSERT INTO time_slot (date, time_id, theme_id) VALUES (DATEADD('DAY', 5, CURRENT_DATE), 3, 7);
INSERT INTO time_slot (date, time_id, theme_id) VALUES (DATEADD('DAY', 4, CURRENT_DATE), 5, 7);
INSERT INTO time_slot (date, time_id, theme_id) VALUES (DATEADD('DAY', 3, CURRENT_DATE), 2, 7);
INSERT INTO time_slot (date, time_id, theme_id) VALUES (DATEADD('DAY', 2, CURRENT_DATE), 4, 7);
INSERT INTO time_slot (date, time_id, theme_id) VALUES (DATEADD('DAY', 1, CURRENT_DATE), 6, 7);
INSERT INTO time_slot (date, time_id, theme_id) VALUES (CURRENT_DATE, 8, 7);
INSERT INTO time_slot (date, time_id, theme_id) VALUES (DATEADD('DAY', 6, CURRENT_DATE), 1, 7);
INSERT INTO time_slot (date, time_id, theme_id) VALUES (DATEADD('DAY', 6, CURRENT_DATE), 2, 13);
INSERT INTO time_slot (date, time_id, theme_id) VALUES (DATEADD('DAY', 5, CURRENT_DATE), 4, 13);
INSERT INTO time_slot (date, time_id, theme_id) VALUES (DATEADD('DAY', 4, CURRENT_DATE), 6, 13);
INSERT INTO time_slot (date, time_id, theme_id) VALUES (DATEADD('DAY', 3, CURRENT_DATE), 8, 13);
INSERT INTO time_slot (date, time_id, theme_id) VALUES (DATEADD('DAY', 2, CURRENT_DATE), 1, 13);
INSERT INTO time_slot (date, time_id, theme_id) VALUES (DATEADD('DAY', 1, CURRENT_DATE), 3, 13);
INSERT INTO time_slot (date, time_id, theme_id) VALUES (DATEADD('DAY', 6, CURRENT_DATE), 4, 25);
INSERT INTO time_slot (date, time_id, theme_id) VALUES (DATEADD('DAY', 4, CURRENT_DATE), 2, 25);
INSERT INTO time_slot (date, time_id, theme_id) VALUES (DATEADD('DAY', 2, CURRENT_DATE), 7, 25);
INSERT INTO time_slot (date, time_id, theme_id) VALUES (CURRENT_DATE, 5, 25);
INSERT INTO time_slot (date, time_id, theme_id) VALUES (DATEADD('DAY', 6, CURRENT_DATE), 3, 19);
INSERT INTO time_slot (date, time_id, theme_id) VALUES (DATEADD('DAY', 5, CURRENT_DATE), 5, 19);
INSERT INTO time_slot (date, time_id, theme_id) VALUES (DATEADD('DAY', 4, CURRENT_DATE), 7, 19);
INSERT INTO time_slot (date, time_id, theme_id) VALUES (DATEADD('DAY', 3, CURRENT_DATE), 1, 19);
INSERT INTO time_slot (date, time_id, theme_id) VALUES (DATEADD('DAY', 2, CURRENT_DATE), 2, 19);
INSERT INTO time_slot (date, time_id, theme_id) VALUES (DATEADD('DAY', 5, CURRENT_DATE), 1, 2);
INSERT INTO time_slot (date, time_id, theme_id) VALUES (DATEADD('DAY', 3, CURRENT_DATE), 3, 2);
INSERT INTO time_slot (date, time_id, theme_id) VALUES (DATEADD('DAY', 1, CURRENT_DATE), 5, 2);
INSERT INTO time_slot (date, time_id, theme_id) VALUES (CURRENT_DATE, 4, 2);
INSERT INTO time_slot (date, time_id, theme_id) VALUES (DATEADD('DAY', 6, CURRENT_DATE), 5, 8);
INSERT INTO time_slot (date, time_id, theme_id) VALUES (DATEADD('DAY', 4, CURRENT_DATE), 8, 8);
INSERT INTO time_slot (date, time_id, theme_id) VALUES (DATEADD('DAY', 2, CURRENT_DATE), 6, 8);
INSERT INTO time_slot (date, time_id, theme_id) VALUES (DATEADD('DAY', 5, CURRENT_DATE), 6, 14);
INSERT INTO time_slot (date, time_id, theme_id) VALUES (DATEADD('DAY', 3, CURRENT_DATE), 7, 14);
INSERT INTO time_slot (date, time_id, theme_id) VALUES (DATEADD('DAY', 1, CURRENT_DATE), 8, 14);
INSERT INTO time_slot (date, time_id, theme_id) VALUES (DATEADD('DAY', 6, CURRENT_DATE), 6, 20);
INSERT INTO time_slot (date, time_id, theme_id) VALUES (DATEADD('DAY', 4, CURRENT_DATE), 4, 20);
INSERT INTO time_slot (date, time_id, theme_id) VALUES (DATEADD('DAY', 2, CURRENT_DATE), 3, 20);
INSERT INTO time_slot (date, time_id, theme_id) VALUES (DATEADD('DAY', 5, CURRENT_DATE), 7, 26);
INSERT INTO time_slot (date, time_id, theme_id) VALUES (DATEADD('DAY', 3, CURRENT_DATE), 5, 26);
INSERT INTO time_slot (date, time_id, theme_id) VALUES (DATEADD('DAY', 6, CURRENT_DATE), 7, 3);
INSERT INTO time_slot (date, time_id, theme_id) VALUES (DATEADD('DAY', 5, CURRENT_DATE), 8, 9);
INSERT INTO time_slot (date, time_id, theme_id) VALUES (DATEADD('DAY', 4, CURRENT_DATE), 1, 15);
INSERT INTO time_slot (date, time_id, theme_id) VALUES (DATEADD('DAY', 3, CURRENT_DATE), 6, 21);
INSERT INTO time_slot (date, time_id, theme_id) VALUES (DATEADD('DAY', 1, CURRENT_DATE), 2, 27);

-- 확정 예약 데이터
INSERT INTO reservation (name, slot_id, created_at) VALUES ('포비', (SELECT id FROM time_slot WHERE date = DATEADD('DAY', 6, CURRENT_DATE) AND time_id = 1 AND theme_id = 1), CAST(CURRENT_DATE || ' 10:00:00' AS TIMESTAMP));
INSERT INTO reservation (name, slot_id, created_at) VALUES ('리사', (SELECT id FROM time_slot WHERE date = DATEADD('DAY', 5, CURRENT_DATE) AND time_id = 2 AND theme_id = 1), CAST(CURRENT_DATE || ' 10:05:00' AS TIMESTAMP));
INSERT INTO reservation (name, slot_id, created_at) VALUES ('브리', (SELECT id FROM time_slot WHERE date = DATEADD('DAY', 4, CURRENT_DATE) AND time_id = 3 AND theme_id = 1), CAST(CURRENT_DATE || ' 10:10:00' AS TIMESTAMP));
INSERT INTO reservation (name, slot_id, created_at) VALUES ('제이슨', (SELECT id FROM time_slot WHERE date = DATEADD('DAY', 3, CURRENT_DATE) AND time_id = 4 AND theme_id = 1), CAST(CURRENT_DATE || ' 10:15:00' AS TIMESTAMP));
INSERT INTO reservation (name, slot_id, created_at) VALUES ('브라운', (SELECT id FROM time_slot WHERE date = DATEADD('DAY', 2, CURRENT_DATE) AND time_id = 5 AND theme_id = 1), CAST(CURRENT_DATE || ' 10:20:00' AS TIMESTAMP));
INSERT INTO reservation (name, slot_id, created_at) VALUES ('네오', (SELECT id FROM time_slot WHERE date = DATEADD('DAY', 1, CURRENT_DATE) AND time_id = 6 AND theme_id = 1), CAST(CURRENT_DATE || ' 10:25:00' AS TIMESTAMP));
INSERT INTO reservation (name, slot_id, created_at) VALUES ('라이언', (SELECT id FROM time_slot WHERE date = CURRENT_DATE AND time_id = 7 AND theme_id = 1), CAST(CURRENT_DATE || ' 10:30:00' AS TIMESTAMP));
INSERT INTO reservation (name, slot_id, created_at) VALUES ('포비', (SELECT id FROM time_slot WHERE date = DATEADD('DAY', 5, CURRENT_DATE) AND time_id = 3 AND theme_id = 7), CAST(CURRENT_DATE || ' 11:00:00' AS TIMESTAMP));
INSERT INTO reservation (name, slot_id, created_at) VALUES ('브리', (SELECT id FROM time_slot WHERE date = DATEADD('DAY', 4, CURRENT_DATE) AND time_id = 5 AND theme_id = 7), CAST(CURRENT_DATE || ' 11:05:00' AS TIMESTAMP));
INSERT INTO reservation (name, slot_id, created_at) VALUES ('제이슨', (SELECT id FROM time_slot WHERE date = DATEADD('DAY', 3, CURRENT_DATE) AND time_id = 2 AND theme_id = 7), CAST(CURRENT_DATE || ' 11:10:00' AS TIMESTAMP));
INSERT INTO reservation (name, slot_id, created_at) VALUES ('네오', (SELECT id FROM time_slot WHERE date = DATEADD('DAY', 2, CURRENT_DATE) AND time_id = 4 AND theme_id = 7), CAST(CURRENT_DATE || ' 11:15:00' AS TIMESTAMP));
INSERT INTO reservation (name, slot_id, created_at) VALUES ('라이언', (SELECT id FROM time_slot WHERE date = DATEADD('DAY', 1, CURRENT_DATE) AND time_id = 6 AND theme_id = 7), CAST(CURRENT_DATE || ' 11:20:00' AS TIMESTAMP));
INSERT INTO reservation (name, slot_id, created_at) VALUES ('리사', (SELECT id FROM time_slot WHERE date = CURRENT_DATE AND time_id = 8 AND theme_id = 7), CAST(CURRENT_DATE || ' 11:25:00' AS TIMESTAMP));
INSERT INTO reservation (name, slot_id, created_at) VALUES ('브라운', (SELECT id FROM time_slot WHERE date = DATEADD('DAY', 6, CURRENT_DATE) AND time_id = 1 AND theme_id = 7), CAST(CURRENT_DATE || ' 11:30:00' AS TIMESTAMP));
INSERT INTO reservation (name, slot_id, created_at) VALUES ('토미', (SELECT id FROM time_slot WHERE date = DATEADD('DAY', 6, CURRENT_DATE) AND time_id = 2 AND theme_id = 13), CAST(CURRENT_DATE || ' 12:00:00' AS TIMESTAMP));
INSERT INTO reservation (name, slot_id, created_at) VALUES ('제인', (SELECT id FROM time_slot WHERE date = DATEADD('DAY', 5, CURRENT_DATE) AND time_id = 4 AND theme_id = 13), CAST(CURRENT_DATE || ' 12:05:00' AS TIMESTAMP));
INSERT INTO reservation (name, slot_id, created_at) VALUES ('포비', (SELECT id FROM time_slot WHERE date = DATEADD('DAY', 4, CURRENT_DATE) AND time_id = 6 AND theme_id = 13), CAST(CURRENT_DATE || ' 12:10:00' AS TIMESTAMP));
INSERT INTO reservation (name, slot_id, created_at) VALUES ('리사', (SELECT id FROM time_slot WHERE date = DATEADD('DAY', 3, CURRENT_DATE) AND time_id = 8 AND theme_id = 13), CAST(CURRENT_DATE || ' 12:15:00' AS TIMESTAMP));
INSERT INTO reservation (name, slot_id, created_at) VALUES ('브리', (SELECT id FROM time_slot WHERE date = DATEADD('DAY', 2, CURRENT_DATE) AND time_id = 1 AND theme_id = 13), CAST(CURRENT_DATE || ' 12:20:00' AS TIMESTAMP));
INSERT INTO reservation (name, slot_id, created_at) VALUES ('제이슨', (SELECT id FROM time_slot WHERE date = DATEADD('DAY', 1, CURRENT_DATE) AND time_id = 3 AND theme_id = 13), CAST(CURRENT_DATE || ' 12:25:00' AS TIMESTAMP));
INSERT INTO reservation (name, slot_id, created_at) VALUES ('포비', (SELECT id FROM time_slot WHERE date = DATEADD('DAY', 6, CURRENT_DATE) AND time_id = 4 AND theme_id = 25), CAST(CURRENT_DATE || ' 14:00:00' AS TIMESTAMP));
INSERT INTO reservation (name, slot_id, created_at) VALUES ('브리', (SELECT id FROM time_slot WHERE date = DATEADD('DAY', 4, CURRENT_DATE) AND time_id = 2 AND theme_id = 25), CAST(CURRENT_DATE || ' 14:05:00' AS TIMESTAMP));
INSERT INTO reservation (name, slot_id, created_at) VALUES ('리사', (SELECT id FROM time_slot WHERE date = DATEADD('DAY', 2, CURRENT_DATE) AND time_id = 7 AND theme_id = 25), CAST(CURRENT_DATE || ' 14:10:00' AS TIMESTAMP));
INSERT INTO reservation (name, slot_id, created_at) VALUES ('네오', (SELECT id FROM time_slot WHERE date = CURRENT_DATE AND time_id = 5 AND theme_id = 25), CAST(CURRENT_DATE || ' 14:15:00' AS TIMESTAMP));
INSERT INTO reservation (name, slot_id, created_at) VALUES ('앨리스', (SELECT id FROM time_slot WHERE date = DATEADD('DAY', 6, CURRENT_DATE) AND time_id = 3 AND theme_id = 19), CAST(CURRENT_DATE || ' 13:00:00' AS TIMESTAMP));
INSERT INTO reservation (name, slot_id, created_at) VALUES ('밥', (SELECT id FROM time_slot WHERE date = DATEADD('DAY', 5, CURRENT_DATE) AND time_id = 5 AND theme_id = 19), CAST(CURRENT_DATE || ' 13:05:00' AS TIMESTAMP));
INSERT INTO reservation (name, slot_id, created_at) VALUES ('찰리', (SELECT id FROM time_slot WHERE date = DATEADD('DAY', 4, CURRENT_DATE) AND time_id = 7 AND theme_id = 19), CAST(CURRENT_DATE || ' 13:10:00' AS TIMESTAMP));
INSERT INTO reservation (name, slot_id, created_at) VALUES ('데이비드', (SELECT id FROM time_slot WHERE date = DATEADD('DAY', 3, CURRENT_DATE) AND time_id = 1 AND theme_id = 19), CAST(CURRENT_DATE || ' 13:15:00' AS TIMESTAMP));
INSERT INTO reservation (name, slot_id, created_at) VALUES ('이브', (SELECT id FROM time_slot WHERE date = DATEADD('DAY', 2, CURRENT_DATE) AND time_id = 2 AND theme_id = 19), CAST(CURRENT_DATE || ' 13:20:00' AS TIMESTAMP));
INSERT INTO reservation (name, slot_id, created_at) VALUES ('제이슨', (SELECT id FROM time_slot WHERE date = DATEADD('DAY', 5, CURRENT_DATE) AND time_id = 1 AND theme_id = 2), CAST(CURRENT_DATE || ' 14:20:00' AS TIMESTAMP));
INSERT INTO reservation (name, slot_id, created_at) VALUES ('브라운', (SELECT id FROM time_slot WHERE date = DATEADD('DAY', 3, CURRENT_DATE) AND time_id = 3 AND theme_id = 2), CAST(CURRENT_DATE || ' 14:25:00' AS TIMESTAMP));
INSERT INTO reservation (name, slot_id, created_at) VALUES ('라이언', (SELECT id FROM time_slot WHERE date = DATEADD('DAY', 1, CURRENT_DATE) AND time_id = 5 AND theme_id = 2), CAST(CURRENT_DATE || ' 14:30:00' AS TIMESTAMP));
INSERT INTO reservation (name, slot_id, created_at) VALUES ('어피치', (SELECT id FROM time_slot WHERE date = CURRENT_DATE AND time_id = 4 AND theme_id = 2), CAST(CURRENT_DATE || ' 14:35:00' AS TIMESTAMP));
INSERT INTO reservation (name, slot_id, created_at) VALUES ('포비', (SELECT id FROM time_slot WHERE date = DATEADD('DAY', 6, CURRENT_DATE) AND time_id = 5 AND theme_id = 8), CAST(CURRENT_DATE || ' 15:00:00' AS TIMESTAMP));
INSERT INTO reservation (name, slot_id, created_at) VALUES ('리사', (SELECT id FROM time_slot WHERE date = DATEADD('DAY', 4, CURRENT_DATE) AND time_id = 8 AND theme_id = 8), CAST(CURRENT_DATE || ' 15:05:00' AS TIMESTAMP));
INSERT INTO reservation (name, slot_id, created_at) VALUES ('브리', (SELECT id FROM time_slot WHERE date = DATEADD('DAY', 2, CURRENT_DATE) AND time_id = 6 AND theme_id = 8), CAST(CURRENT_DATE || ' 15:10:00' AS TIMESTAMP));
INSERT INTO reservation (name, slot_id, created_at) VALUES ('브라운', (SELECT id FROM time_slot WHERE date = DATEADD('DAY', 5, CURRENT_DATE) AND time_id = 6 AND theme_id = 14), CAST(CURRENT_DATE || ' 15:15:00' AS TIMESTAMP));
INSERT INTO reservation (name, slot_id, created_at) VALUES ('네오', (SELECT id FROM time_slot WHERE date = DATEADD('DAY', 3, CURRENT_DATE) AND time_id = 7 AND theme_id = 14), CAST(CURRENT_DATE || ' 15:20:00' AS TIMESTAMP));
INSERT INTO reservation (name, slot_id, created_at) VALUES ('라이언', (SELECT id FROM time_slot WHERE date = DATEADD('DAY', 1, CURRENT_DATE) AND time_id = 8 AND theme_id = 14), CAST(CURRENT_DATE || ' 15:25:00' AS TIMESTAMP));
INSERT INTO reservation (name, slot_id, created_at) VALUES ('토미', (SELECT id FROM time_slot WHERE date = DATEADD('DAY', 6, CURRENT_DATE) AND time_id = 6 AND theme_id = 20), CAST(CURRENT_DATE || ' 15:30:00' AS TIMESTAMP));
INSERT INTO reservation (name, slot_id, created_at) VALUES ('제인', (SELECT id FROM time_slot WHERE date = DATEADD('DAY', 4, CURRENT_DATE) AND time_id = 4 AND theme_id = 20), CAST(CURRENT_DATE || ' 15:35:00' AS TIMESTAMP));
INSERT INTO reservation (name, slot_id, created_at) VALUES ('앨리스', (SELECT id FROM time_slot WHERE date = DATEADD('DAY', 2, CURRENT_DATE) AND time_id = 3 AND theme_id = 20), CAST(CURRENT_DATE || ' 15:40:00' AS TIMESTAMP));
INSERT INTO reservation (name, slot_id, created_at) VALUES ('밥', (SELECT id FROM time_slot WHERE date = DATEADD('DAY', 5, CURRENT_DATE) AND time_id = 7 AND theme_id = 26), CAST(CURRENT_DATE || ' 16:00:00' AS TIMESTAMP));
INSERT INTO reservation (name, slot_id, created_at) VALUES ('찰리', (SELECT id FROM time_slot WHERE date = DATEADD('DAY', 3, CURRENT_DATE) AND time_id = 5 AND theme_id = 26), CAST(CURRENT_DATE || ' 16:05:00' AS TIMESTAMP));
INSERT INTO reservation (name, slot_id, created_at) VALUES ('포비', (SELECT id FROM time_slot WHERE date = DATEADD('DAY', 6, CURRENT_DATE) AND time_id = 7 AND theme_id = 3), CAST(CURRENT_DATE || ' 16:10:00' AS TIMESTAMP));
INSERT INTO reservation (name, slot_id, created_at) VALUES ('리사', (SELECT id FROM time_slot WHERE date = DATEADD('DAY', 5, CURRENT_DATE) AND time_id = 8 AND theme_id = 9), CAST(CURRENT_DATE || ' 16:15:00' AS TIMESTAMP));
INSERT INTO reservation (name, slot_id, created_at) VALUES ('브리', (SELECT id FROM time_slot WHERE date = DATEADD('DAY', 4, CURRENT_DATE) AND time_id = 1 AND theme_id = 15), CAST(CURRENT_DATE || ' 16:20:00' AS TIMESTAMP));
INSERT INTO reservation (name, slot_id, created_at) VALUES ('제이슨', (SELECT id FROM time_slot WHERE date = DATEADD('DAY', 3, CURRENT_DATE) AND time_id = 6 AND theme_id = 21), CAST(CURRENT_DATE || ' 16:25:00' AS TIMESTAMP));
INSERT INTO reservation (name, slot_id, created_at) VALUES ('라이언', (SELECT id FROM time_slot WHERE date = DATEADD('DAY', 1, CURRENT_DATE) AND time_id = 2 AND theme_id = 27), CAST(CURRENT_DATE || ' 16:30:00' AS TIMESTAMP));

-- 대기 예약 데이터
INSERT INTO pending (name, slot_id, created_at) VALUES ('어피치', (SELECT id FROM time_slot WHERE date = DATEADD('DAY', 6, CURRENT_DATE) AND time_id = 1 AND theme_id = 1), CAST(CURRENT_DATE || ' 10:00:10' AS TIMESTAMP));
INSERT INTO pending (name, slot_id, created_at) VALUES ('네오', (SELECT id FROM time_slot WHERE date = DATEADD('DAY', 6, CURRENT_DATE) AND time_id = 1 AND theme_id = 1), CAST(CURRENT_DATE || ' 10:01:15' AS TIMESTAMP));
INSERT INTO pending (name, slot_id, created_at) VALUES ('브리', (SELECT id FROM time_slot WHERE date = DATEADD('DAY', 5, CURRENT_DATE) AND time_id = 3 AND theme_id = 7), CAST(CURRENT_DATE || ' 11:01:00' AS TIMESTAMP));
