create table member
(
    id       bigint generated by default as identity,
    email    varchar(255) UNIQUE                            NOT NULL,
    name     varchar(255)                                   NOT NULL,
    password varchar(255)                                   NOT NULL,
    role     varchar(255) check (role in ('ADMIN', 'USER')) NOT NULL,
    primary key (id)
);
CREATE TABLE reservation_time
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY,
    start_at TIME(6) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE theme
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name        VARCHAR(255) NOT NULL,
    description VARCHAR(1000),
    thumbnail   VARCHAR(255),
    PRIMARY KEY (id)
);

CREATE TABLE reservation
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY,
    date                DATE                                                               NOT NULL,
    member_id           BIGINT                                                             NOT NULL,
    reservation_time_id BIGINT                                                             NOT NULL,
    theme_id            BIGINT                                                             NOT NULL,
    reservation_status  varchar(255) check (reservation_status in ('RESERVED', 'WAITING')) NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT fk_member FOREIGN KEY (member_id) REFERENCES member (id),
    CONSTRAINT fk_reservation_time FOREIGN KEY (reservation_time_id) REFERENCES reservation_time (id),
    CONSTRAINT fk_theme FOREIGN KEY (theme_id) REFERENCES theme (id)
);
