create table member
(
    id       bigint generated by default as identity,
    email    varchar(255) not null unique,
    name     varchar(255),
    password varchar(255),
    role     varchar(255) default 'USER' check (role in ('ADMIN', 'USER')),
    primary key (id)
);
create table reservation_time
(
    id       bigint generated by default as identity,
    start_at time(6) not null,
    primary key (id)
);
create table theme
(
    id          bigint generated by default as identity,
    description varchar(255),
    name        varchar(255),
    thumbnail   varchar(255),
    primary key (id)
);
create table reservation
(
    id        bigint generated by default as identity,
    date      date not null,
    member_id bigint,
    theme_id  bigint,
    time_id   bigint,
    status    varchar(255) default 'CONFIRMATION' check (status in ('CONFIRMATION')),
    primary key (id),
    foreign key (member_id) references member,
    foreign key (theme_id)  references theme,
    foreign key (time_id)   references reservation_time
);
