### 예약 목록 조회 API (어드민)
GET http://localhost:8080/admin/reservations
cookie: token=eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxMDA4IiwibmFtZSI6IuyWtOuTnOuvvCIsInJvbGUiOiJBRE1JTiJ9.QBXPFjmHn0iteRzHlr0Pml3EJLOOW8QKYcT8FY9sTszJluHU0hC3frCUNIEc5A5h0hmJFZD1e4j2y3aj5u8uDg;
host: localhost:8080

### 예약 추가 API (멤버)
POST http://localhost:8080/reservations
cookie: token=eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ0MUB0MS5jb20iLCJuYW1lIjoi7J6s7KaIIiwicm9sZSI6Ik1FTUJFUiIsImV4cCI6MTcxNjU0MDc2N30.zZpmVNdJ1117vqz_FDX-IqOJo5K7aL-IwZVyrV_f9ZdfoZrZUXXeX8rwpd6WdQ0z5VtP0na4-7jbJloT94ESXA;
host: localhost:8080
Content-Type: application/json

{
  "date": "2100-01-21",
  "themeId": 1002,
  "timeId": 1001
}

### 예약 추가 API (어드민)
POST http://localhost:8080/admin/reservations
cookie: token=eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxMDA4IiwibmFtZSI6IuyWtOuTnOuvvCIsInJvbGUiOiJBRE1JTiJ9.QBXPFjmHn0iteRzHlr0Pml3EJLOOW8QKYcT8FY9sTszJluHU0hC3frCUNIEc5A5h0hmJFZD1e4j2y3aj5u8uDg;
host: localhost:8080
Content-Type: application/json

{
  "memberId": 1004,
  "themeId": 1001,
  "date": "2100-01-22",
  "timeId": 1001
}

### 예약 삭제 API (어드민)
DELETE http://localhost:8080/admin/reservations/1001
cookie: token=eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxMDA4IiwibmFtZSI6IuyWtOuTnOuvvCIsInJvbGUiOiJBRE1JTiJ9.QBXPFjmHn0iteRzHlr0Pml3EJLOOW8QKYcT8FY9sTszJluHU0hC3frCUNIEc5A5h0hmJFZD1e4j2y3aj5u8uDg;
host: localhost:8080
