package roomescape.domain.exception;

public enum DomainErrorCode {

    INVALID_INPUT,
    UNAUTHORIZED_RESERVATION,
    PAST_RESERVATION,
    NOT_FOUND_RESERVATION,
    NOT_FOUND_RESERVATION_TIME,
    NOT_FOUND_THEME,
    DUPLICATE_RESERVATION,
    DUPLICATE_RESERVATION_TIME,
    DUPLICATE_THEME_NAME,
    REFERENTIAL_INTEGRITY;
}
