package roomescape.domain.exception;

public enum DomainErrorCode {

    NOT_FOUND_RESERVATION,
    DUPLICATED_RESERVATION,
    SLOT_JUST_TAKEN,
    PAST_RESERVATION_CREATE,
    PAST_RESERVATION_DELETE,

    NOT_FOUND_WAIT,
    DUPLICATED_WAIT,
    WAIT_IS_FULL,

    NOT_FOUND_RESERVATION_TIME,
    DUPLICATED_RESERVATION_TIME,
    REFERENCED_TIME,
    PAST_RESERVATION_TIME_READ,

    NOT_FOUND_THEME,
    REFERENCED_THEME,
    FUTURE_RANKING_PERIOD,
    INVALID_RANKING_PERIOD,
    LONG_RANKING_PERIOD,

    INVALID_INPUT,
}
