package roomescape.domain.exception;

public enum DomainErrorCode {

    NOT_FOUND_RESERVATION,
    DUPLICATED_RESERVATION,
    SLOT_JUST_TAKEN,
    PAST_RESERVATION_CREATE,
    PAST_RESERVATION_DELETE,

    NOT_FOUND_WAIT,
    DUPLICATED_WAIT,
    WAIT_IS_FULL,

    NOT_FOUND_RESERVATION_TIME,
    DUPLICATED_RESERVATION_TIME,
    REFERENCED_TIME,
    PAST_RESERVATION_TIME_READ,

    NOT_FOUND_THEME,
    REFERENCED_THEME,
    FUTURE_RANKING_PERIOD,
    INVALID_RANKING_PERIOD,
    LONG_RANKING_PERIOD,

    NOT_FOUND_PAYMENT_ORDER,
    PAYMENT_AMOUNT_MISMATCH,
    PAYMENT_ALREADY_PROCESSED,
    DUPLICATED_PAYMENT_ORDER,
    PAYMENT_SESSION_EXPIRED,
    INVALID_PAYMENT_REQUEST,
    PAYMENT_GATEWAY_CONFIG_ERROR,
    PAYMENT_REJECTED,
    NOT_FOUND_PAYMENT,
    PAYMENT_RETRYABLE,
    PAYMENT_UNKNOWN,
    PAYMENT_FAILED,

    INVALID_INPUT,
}
