SET REFERENTIAL_INTEGRITY FALSE;

DELETE FROM orders;
DELETE FROM waiting_list;
DELETE FROM reservation;
DELETE FROM reservation_time;
DELETE FROM theme;

ALTER TABLE orders ALTER COLUMN id RESTART WITH 1;
ALTER TABLE waiting_list ALTER COLUMN id RESTART WITH 1;
ALTER TABLE reservation ALTER COLUMN id RESTART WITH 1;
ALTER TABLE reservation_time ALTER COLUMN id RESTART WITH 1;
ALTER TABLE theme ALTER COLUMN id RESTART WITH 1;

SET REFERENTIAL_INTEGRITY TRUE;
