SET REFERENTIAL_INTEGRITY FALSE;

DELETE FROM payment_order;
DELETE FROM reservation;
DELETE FROM waiting;
DELETE FROM reservation_slot;
DELETE FROM reservation_time;
DELETE FROM theme;

ALTER TABLE reservation ALTER COLUMN id RESTART WITH 1;
ALTER TABLE payment_order ALTER COLUMN id RESTART WITH 1;
ALTER TABLE waiting ALTER COLUMN id RESTART WITH 1;
ALTER TABLE reservation_slot ALTER COLUMN id RESTART WITH 1;
ALTER TABLE reservation_time ALTER COLUMN id RESTART WITH 1;
ALTER TABLE theme ALTER COLUMN id RESTART WITH 1;

SET REFERENTIAL_INTEGRITY TRUE;
