SET
REFERENTIAL_INTEGRITY FALSE;

TRUNCATE TABLE reservation;
TRUNCATE TABLE payment_order;
TRUNCATE TABLE member;
TRUNCATE TABLE theme;
TRUNCATE TABLE reservation_time;
TRUNCATE TABLE store;
TRUNCATE TABLE reservation_wait;
TRUNCATE TABLE reservation_history;

ALTER TABLE reservation
    ALTER COLUMN id RESTART WITH 1;
ALTER TABLE payment_order
    ALTER COLUMN id RESTART WITH 1;
ALTER TABLE member
    ALTER COLUMN id RESTART WITH 1;
ALTER TABLE theme
    ALTER COLUMN id RESTART WITH 1;
ALTER TABLE reservation_time
    ALTER COLUMN id RESTART WITH 1;
ALTER TABLE store
    ALTER COLUMN id RESTART WITH 1;
ALTER TABLE reservation_wait
    ALTER COLUMN id RESTART WITH 1;
ALTER TABLE reservation_history
    ALTER COLUMN id RESTART WITH 1;

SET
REFERENTIAL_INTEGRITY TRUE;
