SET REFERENTIAL_INTEGRITY FALSE;
TRUNCATE TABLE payment;
TRUNCATE TABLE reservation_waiting RESTART IDENTITY;
TRUNCATE TABLE reservation RESTART IDENTITY;
TRUNCATE TABLE reservation_time RESTART IDENTITY;
TRUNCATE TABLE theme RESTART IDENTITY;
SET REFERENTIAL_INTEGRITY TRUE;
