package roomescape.exception;

public enum ErrorCode {
    INVALID_INPUT,
    INVALID_PARAMETER,
    PAST_RESERVATION,
    DOMAIN_VALIDATION_FAILED,
    NOT_FOUND,
    RESOURCE_NOT_FOUND,
    CONFLICT,
    FORBIDDEN,
    PAYMENT_AMOUNT_MISMATCH,
    PAYMENT_FAILED,
    PAYMENT_RESULT_UNKNOWN,
    PAYMENT_GATEWAY_UNAVAILABLE,
    PAYMENT_GATEWAY_BUSY,
    INTERNAL_SERVER_ERROR,
}
