package roomescape.exception;

public enum ErrorType {

    INVALID_DOMAIN,
    RESOURCE_NOT_FOUND,
    RESERVATION_OWNER_MISMATCH,
    STORE_MANAGEMENT_FORBIDDEN,
    DUPLICATE_RESERVATION,
    RESERVATION_TIME_IN_USE,
    PAST_DATE_TIME_RESERVATION,
    PAST_RESERVATION_MODIFICATION,
    NON_PAST_RESERVATION_DELETION,
    DUPLICATE_USERNAME,
    INVALID_LOGIN,
    UNAUTHENTICATED,
    UNAUTHORIZED,
    RESERVATION_NOT_FOUND_FOR_WAITING,
    RESERVATION_NOT_RESERVED,
    DUPLICATE_WAITING_RESERVATION,
    DUPLICATE_ORDER_ID,

    INVALID_REQUEST,
    ENDPOINT_NOT_FOUND,
    INTERNAL_SERVER_ERROR
}
